# Site settings
title: Rants of a Tech Proletariat
email: soravis@runnables.co.th
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://5un.co" # the base hostname & protocol for your site
twitter_username: asunnotthesun
github_username:  5un

# Build settings
markdown: kramdown
